# Owner and repository name
  owner: zigbee-team  # Replace with your GitHub org name
  repo: risksentinel-status

  # Sites to monitor
  sites:
    # Public health endpoint
    - name: RiskSentinel API - Health Check
      url: https://api.risksentinel.ai/health
      expectedStatusCodes:
        - 200
      maxResponseTime: 5000

    # Protected endpoints (require API key)
    - name: RiskSentinel API - Events Endpoint
      url: https://api.risksentinel.ai/v1/events?page_size=1
      method: GET
      headers:
        - "x-api-key: $RISKSENTINEL_API_KEY"
        - "Accept: application/json"
      expectedStatusCodes:
        - 200
      maxResponseTime: 5000

    - name: RiskSentinel API - News Endpoint
      url: https://api.risksentinel.ai/v1/news?page_size=1
      method: GET
      headers:
        - "x-api-key: $RISKSENTINEL_API_KEY"
        - "Accept: application/json"
      expectedStatusCodes:
        - 200
      maxResponseTime: 5000

    # Main website
    - name: RiskSentinel Main Website
      url: https://risksentinel.ai
      expectedStatusCodes:
        - 200
      maxResponseTime: 5000

  # Status website configuration
  status-website:
    cname: status.risksentinel.com
    name: RiskSentinel API Status
    logoUrl: https://risksentinel.ai/logo.png
    introTitle: "**RiskSentinel API** Status Page"
    introMessage: |
      Real-time monitoring of RiskSentinel API services. 
      Subscribe to updates or check back here anytime.

    navbar:
      - title: Status
        href: /
      - title: API Documentation
        href: https://risksentinel.ai/docs
      - title: Support
        href: mailto:support@risksentinel.ai

  # Monitoring schedule (every 5 minutes)
  workflowSchedule:
    uptime: "*/5 * * * *"

  # Notifications
  notifications:
    - type: email
      email: support@risksentinel.ai

  # Assignees for incidents
  assignees:
    - olgashi  # Replace with your username
